- name: ensure group
  ansible.builtin.group:
    name: uhr
    state: present
- name: ensure user
  ansible.builtin.user:
    name: uhr
    group: uhr
- name: ensure uhr systemd unit
  register: svc
  copy:
    src: files/uhr.service
    dest: /etc/systemd/system/uhr.service
- name: binary
  register: bin
  copy:
    src: files/wisuhr
    dest: /usr/local/bin/wisuhr
    mode: 0755
- name: start uhr service
  when: bin.changed or svc.changed
  ansible.builtin.systemd:
    state: restarted
    name: uhr
    daemon_reload: yes
