- name: ensure group
  ansible.builtin.group:
    name: parttysh
    state: present
- name: ensure user
  ansible.builtin.user:
    name: parttysh
    group: parttysh
- name: ensure parttysh systemd unit
  register: svc
  copy:
    src: files/parttysh.service
    dest: /etc/systemd/system/parttysh.service
- name: binary
  register: bin
  copy:
    src: files/parttysh
    dest: /usr/local/bin/parttysh
    mode: 0755
- name: start parttysh service
  when: bin.changed or svc.changed
  ansible.builtin.systemd:
    state: restarted
    name: parttysh
    daemon_reload: yes
